import {
  WEBSITE_HITS_BY_URL,
  WEBSITE_VISITORS_BY_REFERRER_URL,
  WEBSITE_HITS_PER_VISITOR,
  CHAT_START_CHAT_FORM_OPEN_COUNT_BY_URL,
  CHAT_LEAVE_MESSAGE_FORM_OPEN_COUNT_BY_URL,
  CHAT_ONLINE_TIME_PER_ACCOUNT,
  CHAT_ACCEPT_CHAT_DELAY_PER_ACCOUNT,
  CHAT_START_CHAT_FORM_FILLOUT_TIME,
  CHAT_LEAVE_MESSAGE_FORM_FILLOUT_TIME,
  CHAT_VISITOR_MESSAGES_COUNT_PER_CHAT,
  CHAT_ALL_OPERATORS_MESSAGES_COUNT_PER_CHAT,
  CHAT_OPERATOR_RESPONSE_TIME_PER_ACCOUNT,
  CHAT_VISITOR_RESPONSE_TIME,
  CHAT_START_CHAT_FORM_OPEN_COUNT,
  CHAT_START_CHAT_FORM_SUBMIT_COUNT,
  CHAT_PRE_CHAT_SURVEY_CLICK_TROUGH_RATE,
  CHAT_LEAVE_MESSAGE_FORM_OPEN_COUNT,
  CHAT_OFFLINE_MESSAGE_COUNT,
  CHAT_OFFLINE_FORM_CLICK_TROUGH_RATE,
  CHAT_CHATS_PER_ACCOUNT,
  CHAT_ACCEPTED_CHATS_PER_ACCOUNT,
  CHAT_ACCEPTANCE_RATE,
  CHAT_MISSED_CALLS_PER_ACCOUNT,
  CHAT_INVITATION_SENT_COUNT_PER_ACCOUNT,
  CHAT_INVITATION_ACCEPT_COUNT_PER_ACCOUNT,
  CHAT_PROACTIVE_ACCEPTANCE_RATE,
  CHAT_INVITATION_DECLINE_COUNT_PER_ACCOUNT,
  CHAT_PCS_PROFICIENCY_PER_ACCOUNT,
  CHAT_PCS_POLITENESS_PER_ACCOUNT,
  CHAT_PCS_CASE_SOLVED_COUNT_PER_ACCOUNT,
  CHAT_PCS_CASE_NOT_SOLVED_COUNT_PER_ACCOUNT,
  CHAT_PCS_CONTENTED_COUNT_PER_ACCOUNT,
  CHAT_PCS_NOT_CONTENTED_COUNT_PER_ACCOUNT,
} from './metrics.js';

export const DEFAULT_TAKE_COUNT = 10;
export const DEFAULT_SKIP_COUNT = 0;
export const DEFAULT_SORT_DIRECTION = 'desc';

export const WEBSITE_COUNTER_METRICS = {
  [WEBSITE_HITS_BY_URL]: 'visitsByURL',
  [WEBSITE_VISITORS_BY_REFERRER_URL]: 'visitsByReferrer',
};

export const WEBSITE_VALUE_METRICS = {
  [WEBSITE_HITS_PER_VISITOR]: 'totalHits',
};

export const CHAT_REFERRERS_COUNTER_METRICS = {
  [CHAT_START_CHAT_FORM_OPEN_COUNT_BY_URL]: 'preChatSurveyReferrers',
  [CHAT_LEAVE_MESSAGE_FORM_OPEN_COUNT_BY_URL]: 'offlineFormReferrers',
};

export const ACCOUNT_REFERRERS_COUNTER_METRICS = {
  [CHAT_START_CHAT_FORM_OPEN_COUNT_BY_URL]: 'preChatSurvey-referrers',
  [CHAT_LEAVE_MESSAGE_FORM_OPEN_COUNT_BY_URL]: 'offlineForm-referrers',
};

export const ACCOUNT_VALUE_METRICS = {
  [CHAT_ONLINE_TIME_PER_ACCOUNT]: 'onlinePresence-chatOnlineTime',
  [CHAT_ACCEPT_CHAT_DELAY_PER_ACCOUNT]: 'averages-chatAcceptTime',
  [CHAT_START_CHAT_FORM_FILLOUT_TIME]: 'averages-preChatSurveyFilloutTime',
  [CHAT_LEAVE_MESSAGE_FORM_FILLOUT_TIME]: 'averages-offlineFormFilloutTime',
  [CHAT_VISITOR_MESSAGES_COUNT_PER_CHAT]: 'averages-visitorMessagesPerChat',
  [CHAT_ALL_OPERATORS_MESSAGES_COUNT_PER_CHAT]: 'averages-operatorMessagesPerChat',
  [CHAT_OPERATOR_RESPONSE_TIME_PER_ACCOUNT]: 'averages-operatorResponseTime',
  [CHAT_VISITOR_RESPONSE_TIME]: 'averages-visitorResponseTime',
  [CHAT_START_CHAT_FORM_OPEN_COUNT]: 'preChatSurvey-loads',
  [CHAT_START_CHAT_FORM_SUBMIT_COUNT]: 'preChatSurvey-submits',
  [CHAT_PRE_CHAT_SURVEY_CLICK_TROUGH_RATE]: 'preChatSurvey-clickThroughRate',
  [CHAT_LEAVE_MESSAGE_FORM_OPEN_COUNT]: 'offlineForm-loads',
  [CHAT_OFFLINE_MESSAGE_COUNT]: 'offlineForm-submits',
  [CHAT_OFFLINE_FORM_CLICK_TROUGH_RATE]: 'offlineForm-clickThroughRate',
  [CHAT_CHATS_PER_ACCOUNT]: 'chats-sent',
  [CHAT_ACCEPTED_CHATS_PER_ACCOUNT]: 'chats-accepted',
  [CHAT_ACCEPTANCE_RATE]: 'chats-acceptanceRate',
  [CHAT_MISSED_CALLS_PER_ACCOUNT]: 'chats-missed',
  [CHAT_INVITATION_SENT_COUNT_PER_ACCOUNT]: 'proactiveChats-sent',
  [CHAT_INVITATION_ACCEPT_COUNT_PER_ACCOUNT]: 'proactiveChats-accepted',
  [CHAT_PROACTIVE_ACCEPTANCE_RATE]: 'proactiveChats-acceptanceRate',
  [CHAT_INVITATION_DECLINE_COUNT_PER_ACCOUNT]: 'proactiveChats-declined',
  [CHAT_PCS_PROFICIENCY_PER_ACCOUNT]: 'postChatSurvey-proficiency',
  [CHAT_PCS_POLITENESS_PER_ACCOUNT]: 'postChatSurvey-politeness',
  [CHAT_PCS_CASE_SOLVED_COUNT_PER_ACCOUNT]: 'postChatSurvey-caseSolved',
  [CHAT_PCS_CASE_NOT_SOLVED_COUNT_PER_ACCOUNT]: 'postChatSurvey-caseNotSolved',
  [CHAT_PCS_CONTENTED_COUNT_PER_ACCOUNT]: 'postChatSurvey-contented',
  [CHAT_PCS_NOT_CONTENTED_COUNT_PER_ACCOUNT]: 'postChatSurvey-notContented',
};
