
import {
  asyncTest,
  NO_STATS_FOR_PAST_TIME_PERIOD,
  NO_STATS_FOR_FUTURE_TIME_PERIOD,
} from './_common'

const methodName = 'getAccountSummary'

asyncTest({
  methodName,
  timePeriod: 'SHORT_TIME_PERIOD',
  callback: res => expect(res).toEqual(PROCESSED_RESPONSE),
})
asyncTest({
  methodName,
  timePeriod: 'SHORT_TIME_PERIOD5',
  callback: res => expect(res).toEqual(PROCESSED_RESPONSE2),
})
asyncTest({
  methodName,
  timePeriod: 'PAST_TIME_PERIOD',
  callback: res => expect(res).toEqual(NO_STATS_FOR_PAST_TIME_PERIOD),
})
asyncTest({
  methodName,
  timePeriod: 'FUTURE_TIME_PERIOD',
  callback: res => expect(res).toEqual(NO_STATS_FOR_FUTURE_TIME_PERIOD),
})

/* OUTPUT */
const PROCESSED_RESPONSE = {
  "chats": {
    "sent": "No statistics for this metric!",
    "missed": "No statistics for this metric!",
    "acceptanceRate": "0%",
    "accepted": "No statistics for this metric!"
  },
  "preChatSurvey": {
    "loads": 1,
    "referrers": {
      "https://www.providesupport.com/": 0,
      "https://www.providesupport.com/integrations/shopify.html": 1
    },
    "clickThroughRate": "0%",
    "submits": "No statistics for this metric!"
  },
  "offlineForm": {
    "clickThroughRate": "No statistics for this metric!",
    "loads": "No statistics for this metric!",
    "submits": "No statistics for this metric!",
    "referrers": "No statistics for this metric!"
  },
  "proactiveChats": {
    "acceptanceRate": "No statistics for this metric!",
    "sent": "No statistics for this metric!",
    "accepted": "No statistics for this metric!",
    "declined": "No statistics for this metric!"
  },
  "onlinePresence": {
    "chatOnlineTime": "No statistics for this metric!",
    "chatOfflineTime": "Not enough statistics to calculate this metric!"
  },
  "averages": {
    "chatAcceptTime": "No statistics for this metric!",
    "preChatSurveyFilloutTime": "No statistics for this metric!",
    "visitorResponseTime": "No statistics for this metric!",
    "offlineFormFilloutTime": "No statistics for this metric!",
    "operatorResponseTime": "No statistics for this metric!",
    "visitorMessagesPerChat": "No statistics for this metric!",
    "operatorMessagesPerChat": "No statistics for this metric!",
    "incomingChatsPerDay": "Not enough statistics to calculate this metric!",
    "incomingChatsPerHour": "Not enough statistics to calculate this metric!",
    "acceptedChatsPerDay": "Not enough statistics to calculate this metric!",
    "acceptedChatsPerHour": "Not enough statistics to calculate this metric!"
  },
  "postChatSurvey": {
    "proficiency": "No statistics for this metric!",
    "politeness": "No statistics for this metric!",
    "caseSolved": "No statistics for this metric!",
    "caseNotSolved": "No statistics for this metric!",
    "contented": "No statistics for this metric!",
    "notContented": "No statistics for this metric!"
  }
}

const PROCESSED_RESPONSE2 = {
  "onlinePresence": {
    "chatOnlineTime": [
      1293202.6,
      "14d 23h 13m 22s"
    ],
    "chatOfflineTime": [
      2797,
      "46m 37s"
    ]
  },
  "averages": {
    "chatAcceptTime": [
      33.73087,
      "33s"
    ],
    "preChatSurveyFilloutTime": [
      59.80261,
      "59s"
    ],
    "visitorMessagesPerChat": 4.8406467,
    "operatorMessagesPerChat": 3.9792147,
    "operatorResponseTime": [
      73.56894,
      "1m 13s",
    ],
    "visitorResponseTime": [
      54.201168,
      "54s",
    ],
    "offlineFormFilloutTime": "No statistics for this metric!",
    "incomingChatsPerDay": 28.80002222223937,
    "incomingChatsPerHour": 1.2000009259266404,
    "acceptedChatsPerDay": 18.800014506184034,
    "acceptedChatsPerHour": 0.783333937757668
  },
  "preChatSurvey": {
    "loads": 1162,
    "submits": 431,
    "clickThroughRate": "37%",
    "referrers": {
      "https://www.providesupport.com/blog/real-time-visitor-monitoring-in-chat-support/": 1,
      "https://www.providesupport.com/": 218,
      "https://www.providesupport.com/blog/customer-service-cheat-sheet-for-live-chat-support-operators-with-examples-of-responses/": 42,
      "https://www.providesupport.cn/": 43,
      "https://www.providesupport.ru/": 2,
      "https://www.providesupport.com/blog/customer-service-dos-and-donts/": 1,
      "https://www.providesupport.com/blog/": 2,
      "https://www.providesupport.com/blog/7-customer-service-challenges/": 1,
      "https://www.providesupport.com/blog/live-chat-etiquette-basics-how-to-ask-questions-correctly/": 1,
      "http://operator.providesupport.com/": 1,
      "https://operator.providesupport.com/action/main/login": 1,
      "https://www.providesupport.com/#": 1,
      "https://www.providesupport.com/blog/10-reasons-customers-complain/": 1,
      "https://www.providesupport.com/blog/positive-phrases-and-empathy-statements-for-customer-service/": 3,
      "https://www.providesupport.com/blog/8-ways-to-say-no-to-customers-with-examples/": 6,
      "https://www.providesupport.com/blog/7-tips-for-maintaining-a-positive-attitude-in-customer-service/": 1,
      "https://www.providesupport.com/blog/how-to-add-a-chat-button-to-blogger/": 6,
      "https://admin7.providesupport.com/zh_CN/view/my-account/operators-and-departments": 1,
      "https://www.providesupport.com/blog/8-simple-ways-to-reach-customers/": 3,
      "https://www.providesupport.com/blog/live-chat-etiquette-10-tips-for-being-polite-on-live-chat/": 1,
      "https://www.providesupport.com/manual/about.htm": 1,
      "https://www.providesupport.com/blog/7-tips-for-more-effective-communication-with-customers-and-coworkers/": 2,
      "https://www.providesupport.com/blog/10-barriers-outstanding-customer-service/": 1,
      "https://www.providesupport.com/blog/history-of-customer-service-and-future-trends-infographic/": 1,
      "https://www.providesupport.cn/manual/current_features.htm": 1,
      "https://www.providesupport.com/blog/how-to-choose-the-right-live-chat-plugin-for-your-wordpress-website/": 1,
      "https://stats.providesupport.com/login": 1,
      "https://www.providesupport.com/manual/chats-reporting.htm": 1,
      "https://www.providesupport.cn/manual/chat_button_codes_overview.htm": 1,
      "https://admin5.providesupport.com/zh_CN/password-sent-confirmation": 1,
      "https://www.providesupport.com/blog/tag/live-chat-etiquette/": 1,
      "https://admin6.providesupport.com/zh_CN/my-account/billing/shopping-cart/shopping-cart": 1,
      "https://admin6.providesupport.com/password-sent-confirmation": 1,
      "https://admin5.providesupport.com/zh_CN/my-account/setup-instructions/direct-link-code-updated": 1,
      "https://admin7.providesupport.com/zh_CN/my-account/billing/shopping-cart/shopping-cart": 1,
      "https://www.providesupport.ru/live-chat-for-iphone": 1,
      "https://admin7.providesupport.com/zh_CN/my-account/billing/payment/bitcoin/thank-you": 1,
      "https://www.providesupport.com.pt/live-chat-integrations/live-chat-for-outlook": 1,
      "https://admin10.providesupport.com/zh_CN/my-account/billing/payment/bitcoin/payment-form": 1,
      "https://admin6.providesupport.com/": 1,
      "https://op.providesupport.com/": 151,
      "https://op.providesupport.com/login": 4,
      "https://admin5.providesupport.com/admin/login": 1,
      "https://op.providesupport.com/password-recovery": 1,
      "https://admin5.providesupport.com/permission-denied": 1,
      "https://www.providesupport.com/signup": 36,
      "https://admin5.providesupport.com/zh_CN/about-us": 1,
      "https://www.providesupport.com/live-chat-pharmacy-site": 17,
      "https://www.providesupport.com/login": 11,
      "https://admin7.providesupport.com/my-account/setup-instructions/noscript-code": 1,
      "https://admin5.providesupport.com/zh_CN/my-account/company/update/profile/update-company-profile-form": 1,
      "https://www.providesupport.cn/login": 4,
      "https://www.providesupport.es/live-chat-pharmacy-site": 4,
      "https://www.providesupport.com/live-support-web-designers": 1,
      "https://www.providesupport.ru/live-chat-canned-responses": 1,
      "https://www.providesupport.cn/password-recovery-form": 2,
      "https://www.providesupport.com/live-chat-pricing": 7,
      "https://admin5.providesupport.com/zh_CN/my-account/dashboard": 2,
      "https://admin6.providesupport.com/zh_CN/my-account/dashboard": 3,
      "https://www.providesupport.com/password-recovery-form": 2,
      "https://admin7.providesupport.com/zh_CN/my-account/dashboard": 7,
      "https://www.providesupport.com/about-us": 1,
      "https://www.providesupport.com/live-bank-customer-service": 4,
      "https://admin5.providesupport.com/my-account/billing/payment/card/update-payment-info-form": 1,
      "https://admin6.providesupport.com/my-account/dashboard": 2,
      "https://admin5.providesupport.com/zh_CN/index": 2,
      "https://admin10.providesupport.com/my-account/dashboard": 3,
      "https://www.providesupport.cn/live-chat-apps": 1,
      "https://www.providesupport.com/live-help-insurance": 8,
      "https://admin7.providesupport.com/zh_CN/my-account/company/update/index": 4,
      "https://admin7.providesupport.com/zh_CN/my-account/setup-instructions/noscript-code": 1,
      "https://www.providesupport.cn/signup": 10,
      "https://www.providesupport.com/web-chat-agent-app": 2,
      "https://admin12.providesupport.com/my-account/dashboard": 2,
      "https://www.providesupport.com/live-chat-window": 10,
      "https://admin9.providesupport.com/my-account/company/update/messenger/update-company-messenger-form": 1,
      "https://admin9.providesupport.com/my-account/dashboard": 4,
      "https://admin11.providesupport.com/my-account/company/update/index": 1,
      "https://www.providesupport.com/live-chat-apps": 3,
      "https://www.providesupport.com/live-chat-for-iphone": 6,
      "https://admin10.providesupport.com/zh_CN/my-account/company/update/messenger/update-company-messenger-form": 1,
      "https://admin12.providesupport.com/index": 1,
      "https://admin11.providesupport.com/live-chat-gallery/post-chat-surveys": 1,
      "https://admin9.providesupport.com/zh_CN/my-account/company/update/index": 1,
      "https://admin11.providesupport.com/zh_CN/my-account/operators-and-departments": 1,
      "https://admin11.providesupport.com/my-account/trial/create-trial-account-confirmation": 1,
      "https://admin10.providesupport.com/zh_CN/my-account/dashboard": 7,
      "https://admin9.providesupport.com/zh_CN/my-account/dashboard": 4,
      "https://www.providesupport.com/spell-checker-in-live-chat": 1,
      "https://admin12.providesupport.com/zh_CN/my-account/setup-instructions/index": 1,
      "https://www.providesupport.cn/my-account/live-demo": 1,
      "https://www.providesupport.com/live-help-education-website": 1,
      "https://www.providesupport.com/live-chat-integrations/live-chat-for-outlook": 1,
      "https://admin9.providesupport.com/zh_CN/my-account/setup-instructions/direct-link-code": 3,
      "https://admin7.providesupport.com/zh_CN/my-account/company/update/messenger/update-company-messenger-form": 2,
      "https://www.providesupport.cn/live-chat-pricing": 8,
      "https://admin11.providesupport.com/zh_CN/my-account/dashboard": 3,
      "https://www.providesupport.com/desktop-chat-agent-app": 2,
      "https://admin7.providesupport.com/my-account/dashboard": 4,
      "https://admin5.providesupport.com/zh_CN/my-account/company/update/messenger/update-company-messenger-form": 1,
      "https://admin5.providesupport.com/zh_CN/my-account/company/update/start-chat-form/start-chat-form-fields": 1,
      "https://admin6.providesupport.com/my-account/canned-response/update-canned-response-form": 1,
      "https://www.providesupport.com/live-chat-video-tutorials": 2,
      "https://www.providesupport.jp/case-studies/ma4salebyowner": 1,
      "https://admin11.providesupport.com/my-account/dashboard": 3,
      "https://admin11.providesupport.com/my-account/live-demo": 1,
      "https://www.providesupport.fr/live-chat-pharmacy-site": 1,
      "https://www.providesupport.com/live-chat-visitor-monitoring": 1,
      "https://www.providesupport.com/live-help-real-estate-website": 10,
      "https://admin10.providesupport.com/zh_CN/index": 1,
      "https://admin7.providesupport.com/zh_CN/my-account/live-demo": 1,
      "https://admin5.providesupport.com/zh_CN/my-account/operators-and-departments": 6,
      "https://admin7.providesupport.com/my-account/trial/create-trial-account-confirmation": 1,
      "https://admin10.providesupport.com/zh_CN/my-account/company/update/index": 3,
      "https://www.providesupport.cn/desktop-chat-agent-app": 1,
      "https://www.providesupport.com/live-chat-integrations": 2,
      "https://admin9.providesupport.com/my-account/live-demo": 2,
      "https://www.providesupport.com/chat-agent-app-for-linux": 4,
      "https://admin10.providesupport.com/zh_CN/my-account/setup-instructions/index": 2,
      "https://admin6.providesupport.com/zh_CN/my-account/trial/create-trial-account-confirmation": 1,
      "https://admin6.providesupport.com/my-account/trial/create-trial-account-confirmation": 1,
      "https://www.providesupport.cn/live-chat-apps/releases": 1,
      "https://admin11.providesupport.com/zh_CN/index": 3,
      "https://admin6.providesupport.com/zh_CN/my-account/company/update/index": 2,
      "https://admin10.providesupport.com/my-account/trial/create-trial-account-confirmation": 1,
      "https://www.providesupport.com/faq": 5,
      "https://admin6.providesupport.com/zh_CN/my-account/billing/shopping-cart/add-standard-package": 2,
      "https://www.providesupport.cn/web-chat-agent-app": 1,
      "https://admin11.providesupport.com/zh_CN/my-account/trial/create-trial-account-confirmation": 1,
      "https://admin10.providesupport.com/zh_CN/about-us": 1,
      "https://www.providesupport.cn/live-support-hosting": 1,
      "https://admin12.providesupport.com/zh_CN/my-account/company/update/messenger/update-company-messenger-form": 2,
      "https://admin9.providesupport.com/zh_CN/my-account/operators-and-departments": 1,
      "https://admin7.providesupport.com/zh_CN/my-account/setup-instructions/custom-images-code": 1,
      "https://www.providesupport.com/live-chat-for-android": 9,
      "https://www.providesupport.cn/about-us": 1,
      "https://www.providesupport.cn/faq": 2,
      "https://admin5.providesupport.com/my-account/setup-instructions/index": 2,
      "https://admin11.providesupport.com/zh_CN/my-account/canned-response/canned-response-list": 2,
      "https://www.providesupport.com/live-chat-car-rental": 3,
      "https://admin10.providesupport.com/my-account/company/update/transcript/update-company-transcript-form": 1,
      "https://admin10.providesupport.com/my-account/company/update/index": 1,
      "https://admin11.providesupport.com/zh_CN/my-account/billing/upgrade": 1,
      "https://www.providesupport.com/live-government-helpdesk": 2,
      "https://admin6.providesupport.com/my-account/canned-response/canned-response-list": 1,
      "https://admin6.providesupport.com/zh_CN/my-account/billing/payment/alipay/alipay-update-billing-contact": 1,
      "https://admin7.providesupport.com/zh_CN/my-account/company/update/system-messages/update-company-messages-form": 1,
      "https://www-providesupport-com.translate.goog/blog/10-barriers-outstanding-customer-service/": 1,
      "https://www.providesupport.fr/live-chat-integrations/live-chat-for-outlook": 1,
      "https://www.providesupport.de/live-chat-pharmacy-site": 1,
      "https://admin6.providesupport.com/my-account/live-demo": 2,
      "https://admin10.providesupport.com/my-account/company/update/messenger/update-company-messenger-form": 1,
      "https://admin12.providesupport.com/permission-denied": 2,
      "https://admin5.providesupport.com/zh_CN/my-account/billing/shopping-cart/add-standard-package": 2,
      "https://admin7.providesupport.com/zh_CN/about-us": 1,
      "https://www.providesupport.cn/live-chat-integrations": 1,
      "https://www.providesupport.com/live-chat-auto-sales": 3,
      "https://admin7.providesupport.com/zh_CN/my-account/billing/upgrade": 1,
      "https://admin12.providesupport.com/zh_CN/my-account/company/update/chat-invitation/update-chat-invitation-form": 1,
      "https://admin7.providesupport.com/my-account/operators-and-departments": 2,
      "https://admin12.providesupport.com/my-account/setup-instructions/noscript-code": 1,
      "https://admin12.providesupport.com/zh_CN/my-account/setup-instructions/direct-link-code": 2,
      "https://www.providesupport.com/live-chat-features": 5,
      "https://www.providesupport.com/live-support-consulting": 3,
      "https://www.providesupport.cn/my-account/billing/shopping-cart/add-standard-package": 1,
      "https://admin10.providesupport.com/zh_CN/my-account/company/update/system-messages/update-company-messages-form": 1,
      "https://admin9.providesupport.com/zh_CN/my-account/company/update/messenger/update-company-messenger-form": 2,
      "https://admin7.providesupport.com/my-account/company/update/chat-messenger-style/update-company-chat-messenger-style-form": 2,
      "https://admin7.providesupport.com/zh_CN/my-account/company/update/call-distribution/update-company-call-distribution-form": 1,
      "https://admin10.providesupport.com/my-account/live-chat-affiliate-partnership/referrals": 1,
      "https://www.providesupport.com/index": 2,
      "https://admin12.providesupport.com/zh_CN/my-account/canned-response/canned-response-list": 1,
      "https://admin11.providesupport.com/zh_CN/my-account/billing/index": 2,
      "https://admin6.providesupport.com/zh_CN/my-account/company/update/connection/update-company-connection-form": 1,
      "https://admin10.providesupport.com/desktop-chat-agent-app": 1,
      "https://admin7.providesupport.com/zh_CN/my-account/company/update/connection/update-company-connection-form": 1,
      "https://admin10.providesupport.com/zh_CN/my-account/setup-instructions/direct-link-code": 1,
      "https://www.providesupport.com/news/live-chat-news-2022": 1,
      "https://admin9.providesupport.com/my-account/operator/number-of-operators-exceeded": 1,
      "https://admin12.providesupport.com/live-chat-gallery/header-pictures": 1,
      "https://admin7.providesupport.com/de/my-account/live-demo": 1,
      "https://www.providesupport.cn/manual/data-overview.htm": 1,
      "https://admin10.providesupport.com/zh_CN/my-account/company/update/analytics/update-company-analytics-form": 1,
      "https://www.providesupport.cn/index": 2,
      "https://admin6.providesupport.com/my-account/how-to-start": 1,
      "https://admin6.providesupport.com/articles": 1,
      "https://admin10.providesupport.com/zh_CN/my-account/company/update/chat-stats/update-chat-stats-form": 1,
      "https://admin9.providesupport.com/zh_CN/my-account/company/update/chat-stats/update-chat-stats-form": 1,
      "https://admin5.providesupport.com/zh_CN/my-account/setup-instructions/standard-code": 1,
      "https://admin12.providesupport.com/my-account/billing/shopping-cart/add-standard-package": 1,
      "https://admin6.providesupport.com/zh_CN/my-account/billing/index": 1,
      "https://admin6.providesupport.com/my-account/company/update/chat-messenger-style/update-company-chat-messenger-style-form": 1,
      "https://admin6.providesupport.com/my-account/company/update/messenger/update-company-messenger-form": 1,
      "https://www.providesupport.com/#lg=1&slide=0": 3,
      "https://admin9.providesupport.com/zh_CN/my-account/trial/create-trial-account-confirmation": 1,
      "https://admin9.providesupport.com/my-account/company/update/system-messages/update-company-messages-form": 1,
      "https://admin7.providesupport.com/zh_CN/my-account/company/update/access-restrictions/update-messenger-access-restrictions-form": 1,
      "https://admin9.providesupport.com/zh_CN/my-account/billing/shopping-cart/add-standard-package": 1,
      "https://admin10.providesupport.com/zh_CN/signup": 1,
      "https://www.providesupport.com/managing-chat-agent-profiles": 1,
      "https://admin10.providesupport.com/zh_CN/web-chat-agent-app": 1,
      "https://admin11.providesupport.com/zh_CN/my-account/operator/update-operator-form": 1,
      "https://admin9.providesupport.com/about-us": 1,
      "https://admin9.providesupport.com/my-account/company/update/call-distribution/update-company-call-distribution-form": 1,
      "https://admin9.providesupport.com/zh_CN/my-account/billing/invoice/invoice-details": 1,
      "https://admin7.providesupport.com/zh_CN/my-account/setup-instructions/direct-link-code-updated": 1,
      "https://admin6.providesupport.com/zh_CN/my-account/billing/invoice/invoice-details": 1,
      "https://www.providesupport.com/live-chat-canned-responses": 1,
      "https://www.providesupport.fr/live-chat-integrations/live-chat-for-joomla": 2,
      "https://www.providesupport.com/blog/10-shopify-apps-for-better-customer-experience/": 1,
      "https://admin10.providesupport.com/my-account/billing/invoice/invoice-details": 1,
      "https://admin7.providesupport.com/zh_CN/my-account/company/update/chat-invitation/update-chat-invitation-form": 1,
      "https://admin9.providesupport.com/my-account/company/update/analytics/update-company-analytics-form": 1,
      "https://www.providesupport.com/chat-online-presence-monitoring": 1,
      "https://admin5.providesupport.com/zh_CN/my-account/billing/invoice/invoice-details": 1,
      "https://admin10.providesupport.com/zh_CN/my-account/billing/upgrade": 1,
      "https://www.providesupport.cn/help/troubleshooting": 1,
      "https://www.providesupport.com/blog/handle-angry-customers-infographic/": 1,
      "https://admin10.providesupport.com/zh_CN/login": 1,
      "https://admin11.providesupport.com/zh_CN/my-account/billing/payment/card/payment-form": 1,
      "https://www.providesupport.cn/live-chat-affiliate-partnership": 1,
      "https://www.providesupport.ru/live-chat-window": 1,
      "https://admin12.providesupport.com/zh_CN/my-account/billing/invoice/invoice-details": 1,
      "https://admin5.providesupport.com/my-account/company/update/start-chat-form/start-chat-form-fields": 1,
      "https://www.providesupport.com/my-account/company/update/leave-message-form/leave-message-form-fields": 1,
      "https://www.providesupport.fr/login": 1,
      "https://www.providesupport.com.pt/live-chat-integrations/live-chat-for-pinnaclecart": 1,
      "https://admin10.providesupport.com/zh_CN/my-account/setup-instructions/textlink-code": 2,
      "https://admin5.providesupport.com/my-account/billing/shopping-cart/number-of-operators-exceeded": 1,
      "https://admin7.providesupport.com/zh_CN/my-account/canned-response/create-canned-response-form": 1,
      "https://www.providesupport.com/articles/live-chat-cheat-sheet-for-customer-service-agents-with-examples": 1,
      "https://admin7.providesupport.com/zh_CN/live-chat-pricing": 1,
      "https://admin6.providesupport.com/my-account/billing/invoice/invoice-details": 1,
      "https://admin7.providesupport.com/zh_CN/my-account/billing/invoice/invoice-details": 1,
      "https://admin9.providesupport.com/my-account/billing/payment/card/payment-info": 1,
      "https://www.providesupport.com/blog/best-practice-for-using-operator-picture-for-chats/": 1,
      "https://admin7.providesupport.com/zh_CN/my-account/setup-instructions/direct-link-code": 1,
      "https://admin12.providesupport.com/zh_CN/my-account/billing/index": 1,
      "https://admin7.providesupport.com/zh_CN/my-account/setup-instructions/index": 1,
      "https://admin11.providesupport.com/zh_CN/my-account/company/update/index": 1,
      "https://www.providesupport.de/live-chat-integrations/live-chat-for-outlook": 1,
      "https://admin7.providesupport.com/my-account/company/update/index": 1,
      "https://admin5.providesupport.com/zh_CN/zh_CN/my-account/billing/payment/alipay/thank-you": 1,
      "https://admin5.providesupport.com/zh_CN/my-account/live-demo": 1,
      "https://admin10.providesupport.com/live-chat-apps": 1,
      "https://admin6.providesupport.com/zh_CN/my-account/setup-instructions/direct-link-code": 1,
      "https://www.providesupport.cn/my-account/billing/index": 1,
      "https://admin6.providesupport.com/zh_CN/desktop-chat-agent-app": 1,
      "http://vm.providesupport.com/": 1,
      "https://admin7.providesupport.com/zh_CN/live-support-consulting": 1,
      "https://admin12.providesupport.com/zh_CN/live-chat-features": 1
    }
  },
  "chats": {
    "sent": 432,
    "accepted": 282,
    "acceptanceRate": "65%",
    "missed": 150
  },
  "postChatSurvey": {
    "proficiency": {
      "average": 4.714286,
      "total": 165
    },
    "politeness": {
      "average": 4.742857,
      "total": 166
    },
    "caseSolved": "No statistics for this metric!",
    "caseNotSolved": "No statistics for this metric!",
    "contented": "No statistics for this metric!",
    "notContented": "No statistics for this metric!"
  },
  "offlineForm": {
    "loads": "No statistics for this metric!",
    "submits": "No statistics for this metric!",
    "clickThroughRate": "No statistics for this metric!",
    "referrers": "No statistics for this metric!"
  },
  "proactiveChats": {
    "sent": "No statistics for this metric!",
    "accepted": "No statistics for this metric!",
    "acceptanceRate": "No statistics for this metric!",
    "declined": "No statistics for this metric!"
  }
}
