 
import {
  asyncTest,
  NO_STATS_FOR_PAST_TIME_PERIOD,
  NO_STATS_FOR_FUTURE_TIME_PERIOD,
} from './_common'

const methodName = 'getPreChatSurveySummary'

asyncTest({
  methodName,
  timePeriod: 'SHORT_TIME_PERIOD2',
  callback: res => expect(res).toEqual(PROCESSED_RESPONSE),
})
asyncTest({
  methodName,
  timePeriod: 'PAST_TIME_PERIOD',
  callback: res => expect(res).toEqual(NO_STATS_FOR_PAST_TIME_PERIOD),
})
asyncTest({
  methodName,
  timePeriod: 'FUTURE_TIME_PERIOD',
  callback: res => expect(res).toEqual(NO_STATS_FOR_FUTURE_TIME_PERIOD),
})

/* OUTPUT */
const PROCESSED_RESPONSE = {
  "loads": 693,
  "submits": 49,
  "referrers": {
    "https://admin9.providesupport.com/zh_CN/view/my-account/billing/payment/alipay/alipay-update-billing-contact": 2,
    "https://www.providesupport.com/": 452,
    "https://admin7.providesupport.com/help/troubleshooting/index.html": 1,
    "https://www.providesupport.com/blog/customer-service-cheat-sheet-for-live-chat-support-operators-with-examples-of-responses/": 11,
    "https://admin7.providesupport.com/view/index": 2,
    "https://www.providesupport.cn/": 26,
    "https://admin11.providesupport.com/view/my-account/company/update/index": 2,
    "https://www.providesupport.com/live-chat-pharmacy-site.html": 6,
    "https://www.providesupport.com/live-help-insurance.html": 1,
    "https://admin12.providesupport.com/view/my-account/dashboard": 1,
    "https://www.providesupport.com/product/testimonials.html": 6,
    "https://admin7.providesupport.com/view/index.html": 1,
    "https://www.providesupport.cn/view/index": 4,
    "https://admin6.providesupport.com/view/zh_CN/my-account/dashboard": 5,
    "https://admin8.providesupport.com/view/index": 1,
    "https://www.providesupport.com/signup/index.html": 1,
    "https://admin8.providesupport.com/zh_CN/view/my-account/company/update/system-messages/update-company-messages-form": 2,
    "https://www.providesupport.com/blog/b2b-customer-experience-get-right/": 1,
    "https://www.providesupport.com/manual/current_features.htm": 4,
    "https://admin5.providesupport.com/view/index": 2,
    "https://admin7.providesupport.com/view/my-account/dashboard": 2,
    "https://admin7.providesupport.com/view/my-account/trial/create-trial-account-confirmation": 1,
    "https://admin9.providesupport.com/view/index.html": 1,
    "https://admin11.providesupport.com/view/my-account/dashboard": 4,
    "https://admin9.providesupport.com/zh_CN/view/my-account/company/update/index": 1,
    "https://www.providesupport.com/blog/8-simple-ways-to-reach-customers/": 1,
    "https://admin5.providesupport.com/zh_CN/view/my-account/billing/shopping-cart/add-standard-package": 1,
    "https://admin5.providesupport.com/zh_CN/view/my-account/how-to-start": 1,
    "https://admin8.providesupport.com/view/my-account/operators-and-departments": 1,
    "https://admin8.providesupport.com/zh_CN/view/my-account/canned-response/canned-response-list": 1,
    "https://admin11.providesupport.com/view/my-account/company/update/images/update-company-images-form": 1,
    "https://admin7.providesupport.com/zh_CN/view/my-account/how-to-start": 1,
    "https://admin9.providesupport.com/zh_CN/view/my-account/operators-and-departments": 1,
    "https://admin9.providesupport.com/view/my-account/company/update/chat-messenger-style/update-company-chat-messenger-style-form": 2,
    "https://admin6.providesupport.com/view/signup/index.html": 2,
    "https://admin8.providesupport.com/zh_CN/view/my-account/billing/shopping-cart/add-standard-package": 1,
    "https://www.providesupport.com/product/testimonials-page2.html": 1,
    "https://admin9.providesupport.com/zh_CN/view/my-account/setup-instructions/index": 2,
    "https://admin6.providesupport.com/zh_CN/view/my-account/billing/payment/card/update-payment-info-form": 1,
    "https://admin8.providesupport.com/zh_CN/view/my-account/company/update/call-distribution/update-company-call-distribution-form": 1,
    "https://www.providesupport.com/live-chat-integrations/index.html": 3,
    "https://www.providesupport.com/live-chat-pricing/index.html": 1,
    "https://www.providesupport.com/live-chat-download/releases/index.html": 1,
    "https://www.providesupport.com/live-chat-download/native-operator-console.html": 3,
    "https://www.providesupport.com/live-chat-gallery/chat-icons-en.html": 1,
    "https://www.providesupport.com/live-chat-features/google-analytics-and-live-chat.html": 1,
    "https://www.providesupport.com/live-chat-screenshots/operator-console.html": 2,
    "https://www.providesupport.cn/live-chat-features/customization.html": 1,
    "https://www.providesupport.cn/live-chat-screenshots/operator-console.html": 1,
    "https://www.providesupport.com/live-chat-integrations/live-chat-for-drupal.html": 1,
    "https://www.providesupport.cn/live-chat-integrations/wordpress.html": 1,
    "https://admin6.providesupport.com/zh_CN/live-chat-affiliate-partnership/index.html": 2,
    "https://admin6.providesupport.com/zh_CN/view/zh_CN/my-account/billing/payment/card/update-payment-info-form": 1,
    "https://www.providesupport.es/live-chat-integrations/index.html": 1,
    "https://www.providesupport.com.pt/live-chat-integrations/live-chat-for-prestashop.html": 1,
    "https://www.providesupport.com/live-support-web-designers.html": 2,
    "https://admin9.providesupport.com/view/zh_CN/my-account/dashboard": 1,
    "https://www.providesupport.com/live-help-education-website.html": 1,
    "https://www.providesupport.com/blog/15-mistakes-of-customer-service-professionals/": 1,
    "https://www.providesupport.com/faq.html": 1,
    "https://www.providesupport.cn/faq.html": 1,
    "https://www.providesupport.com/news/live-chat-news-2019.html": 2,
    "https://admin7.providesupport.com/zh_CN/view/my-account/company/update/offline/update-company-offline-form": 1,
    "https://admin7.providesupport.com/zh_CN/view/my-account/company/update/post-chat-survey/update-company-post-chat-survey-form": 2,
    "https://admin12.providesupport.com/view/index.html": 1,
    "https://www.providesupport.com/password-recovery-form.html": 2,
    "https://www.providesupport.fr/": 1,
    "https://www.providesupport.com/blog/chat-link-on-linkedin/": 1,
    "https://admin12.providesupport.com/zh_CN/view/my-account/company/update/leave-message-form/leave-message-form-fields": 1,
    "https://admin7.providesupport.com/zh_CN/view/zh_CN/my-account/canned-response/update-canned-response-form": 1,
    "https://admin7.providesupport.com/zh_CN/view/zh_CN/my-account/canned-response/update-canned-response-confirmation": 2,
    "https://www.providesupport.com/manual/about_the_system.htm": 1,
    "https://admin8.providesupport.com/zh_CN/index.html": 1,
    "https://www.providesupport.com/blog/10-reasons-customers-complain/": 1,
    "https://admin7.providesupport.com/zh_CN/view/my-account/operators-and-departments": 4,
    "https://www.providesupport.com/live-government-helpdesk.html": 1,
    "https://admin7.providesupport.com/zh_CN/view/my-account/company/update/index": 4,
    "https://admin10.providesupport.com/view/my-account/live-demo": 5,
    "https://www.providesupport.de/": 4,
    "https://www.providesupport.com/blog/5-examples-of-how-live-chat-can-be-utilized/": 1,
    "https://admin7.providesupport.com/zh_CN/view/my-account/dashboard": 2,
    "https://admin7.providesupport.com/zh_CN/view/my-account/canned-response/canned-response-list": 18,
    "https://www.providesupport.cn/product/testimonials.html": 1,
    "https://admin7.providesupport.com/zh_CN/view/my-account/company/update/start-chat-form/start-chat-form-fields": 1,
    "https://admin10.providesupport.com/view/my-account/operators-and-departments": 2,
    "https://admin7.providesupport.com/zh_CN/view/my-account/company/update/images/update-company-images-form": 1,
    "https://admin7.providesupport.com/zh_CN/view/my-account/company/update/system-messages/update-company-messages-form": 1,
    "https://admin10.providesupport.com/view/my-account/company/update/start-chat-form/start-chat-form-fields": 1,
    "https://admin7.providesupport.com/zh_CN/view/my-account/company/update/profile/update-company-profile-form": 1,
    "https://www.providesupport.com/blog/top-benefits-of-using-embedded-chat-window-on-your-website/": 1,
    "https://admin10.providesupport.com/view/my-account/operator/update-operator-form": 1,
    "https://admin7.providesupport.com/zh_CN/view/my-account/company/update/leave-message-form/leave-message-form-fields": 1,
    "https://admin7.providesupport.com/zh_CN/view/my-account/company/update/privacy/update-privacy-form": 2,
    "https://www.providesupport.cn/live-chat-download/native-operator-console.html": 1,
    "https://www.providesupport.com/live-chat-integrations/joomla.html": 1,
    "https://admin7.providesupport.com/zh_CN/view/zh_CN/my-account/canned-response/create-canned-response-form": 11,
    "https://admin7.providesupport.com/zh_CN/view/zh_CN/my-account/canned-response/create-canned-response-confirmation": 10,
    "https://admin7.providesupport.com/zh_CN/view/zh_CN/my-account/canned-response/canned-response-list": 2,
    "https://admin7.providesupport.com/zh_CN/view/my-account/canned-response/bulk-import-csv-canned-response-form": 1,
    "https://admin7.providesupport.com/zh_CN/view/my-account/company/update/call-distribution/update-company-call-distribution-form": 1,
    "https://admin7.providesupport.com/zh_CN/view/zh_CN/my-account/company/update/post-chat-survey/update-company-post-chat-survey-confirmation": 1,
    "https://www.providesupport.cn/live-chat-download/releases/index.html": 1,
    "https://admin6.providesupport.com/de/view/my-account/setup-instructions/custom-images-code": 1,
    "https://admin10.providesupport.com/view/my-account/company/update/start-chat-form/update-field": 3,
    "https://admin10.providesupport.com/view/my-account/company/update/start-chat-form/delete-field": 1
  },
  "clickThroughRate": "7%"
};
